config/routes.rb
GLAC::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get 'signin' => 'devise/sessions#new'
    get 'signout' => 'devise/sessions#destroy'
    get 'signup' => 'devise/registrations#new'
  end

  resources :profiles
  resources :projects
  resources :relations

  root :to => 'pages#home'

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  #has_and_belongs_to_many :projects

  has_many :relations
  has_many :projects, :through => :relations
end

app/models/project.rb
class Project < ActiveRecord::Base
  #has_and_belongs_to_many :profiles

  has_many :relations
  has_many :profiles, :through => :relations
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :profile
  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_one :profile, :dependent => :destroy

  after_create :create_profile

  def create_profile
    Profile.create("user_id" => id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  # Devise overrides
  def after_sign_in_path_for(user)
    edit_profile_path(user.profile)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Welcome to SVSIN"
    @profile = current_user.profile if user_signed_in?
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :profile_init, :only => [:edit, :update, :show]
  before_filter :correct_user, :only => [:edit, :update]

  def index
    @title = "All Users"
    @profiles = Profile.page(params[:page]).per(20)
  end

  def edit
    @title = "Edit user"
  end

  def update
    if @profile.update_attributes(params[:profile])
      flash[:notice] = "Profile successfully updated."
      redirect_to edit_profile_path
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def show
    @title = @profile.name
  end

  private
    def profile_init
      @profile = Profile.find(params[:id])
    end

    def correct_user
      redirect_to(root_path) unless current_user == (@profile.user if @profile)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @projects = Project.page(params[:page]).per(10)
    @title = "All Projects"
  end

  def new
    @title = "Create a new project"
    @project = current_user.profile.projects.new
  end

  def create
    @project = current_user.profile.projects.create(params[:project])
    if @project
      @project.relations.first.relationship = "Champion"
      flash[:success] = "Project was successfully created."
      redirect_to (@project)
    else
      @title = "Create a new project"
      render 'new'
    end
  end

  def show
    @project = Project.find(params[:id])
    @title = @project.title
    @relation = Relation.where(:profile_id => current_user.profile.id, 
                               :project_id => @project.id).first
    @new_relation = Relation.new if @relation.blank?
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    def create
      build_resource

      if resource.save
        if resource.active_for_authentication?
          set_flash_message :notice, :signed_up if is_navigational_format?
          sign_in(resource_name, resource)
          respond_with resource, :location => after_sign_up_path_for(resource)
        else
          set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
          expire_session_data_after_sign_in!
          respond_with resource, :location => after_inactive_sign_up_path_for(resource)
        end
      else
        clean_up_passwords resource
        flash[:error] = flash[:error].to_a.concat resource.errors.full_messages
        redirect_to signup_path
      end
    end
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  before_filter :authenticate_user!
  #before_filter :authorized_user, :only => :destroy

  def create
    @relation = Relation.new(params[:relation])
    if @relation.save
      flash.now[:success] = "You are now supporting this project"
      redirect_to @relation.project
    else
      flash.now[:error] = "An error occured, you can't support this project. ):"
      redirect_to @relation.project
    end
  end

  def destroy
    @relation = Relation.find(params[:id])
    @relation.destroy
    redirect_to projects_path
    flash.now[:error] = "You have now withdrew your support ):"
  end

  private
    def authorized_user
      @relation = current_user.profile.relation.find_by_id(params[:id])
      redirect_to root_path if @relation.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
  case level
  when :notice then 'info'
  when :error then 'error'
  when :alert then 'warning'
  end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_sidebar.html.erb
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Projects</li>
      <li><%= link_to "New Project", new_project_path %></li>
      <li><%= link_to "All Projects", projects_path %></li>
      <li class="nav-header">Profiles</li>
      <li><%= link_to "Your Profile", edit_profile_path(current_user.profile) %></li>
      <li><%= link_to "All Profiles", profiles_path %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>SVSIN</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.0.1/bootstrap.min.js" %>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="i-bar"></span>
            <span class="i-bar"></span>
            <span class="i-bar"></span>
          </a>
          <a class="brand" href="/">SVSIN</a>
          <div class="container nav-collapse">
            <% if user_signed_in?  %>
              <p class="navbar-text pull-right">
                Signed in as <%= link_to current_user.email, 
                                         edit_profile_path(current_user.profile) %>
                <%= link_to "Sign out", signout_path %>
              </p>
            <% else %>
              <p class="navbar-text pull-right">
                <%= link_to "Sign up", signup_path %> or
                <%= link_to "Sign in", signin_path %>
              </p>
            <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="content">
          <div class="row">
            <% if user_signed_in?  %>
              <%= render 'layouts/sidebar' %>
              <div class="span6">
            <% else %>
              <div class="span6 offset3">
            <% end %>
            <% [:notice, :error, :alert].each do |level| %>
            <% unless flash[level].blank? %>
              <div data-alert="alert" class="alert alert-<%= flash_class(level) %> fade in">
                <a class="close" data-dismiss="alert" href="#">&times;</a>
                <%= content_tag :p, flash[level] %>
              </div>
              <% end %>
            <% end %>
            <%= yield %>
            </div>
          </div>
        </div>

      <footer>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="row">
  <div class="span6">
    <div class="boxes">
      <legend><%= @title %></legend>
      Welcome to Silicon Valley Social Innovation Network,
      the simple social network to help you post your 
      social innovation ideas!
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="span6">
    <div class="boxes">
      <%= form_for @profile, :html => {:multipart => true,
                                       :class => "form-horizontal"} do |f| %>
        <% if @profile.errors.any? %>
          <div class="alert alert-error">
          <% @profile.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
          <% end %>
          </div>
        <% end %>

        <fieldset>
          <legend>Basic Information</legend>
          <div class="control-group">
            <%= f.label :name, :class => "control-label" %>
            <div class="controls"><%= f.text_field :name %></div>
          </div>
          <div class="control-group">
            <%= f.label "Organization", :class => "control-label" %>
            <div class="controls"><%= f.text_field :entity %></div>
          </div>
          <div class="control-group">
            <%= f.label "Entity", :class => "control-label" %>
            <div class="controls">
              <%= f.select :orgtype, { "Government" => "Government",
                                           "University" => "University", 
                                           "Non-profit" => "Non-profit",
                                           "Private" => "Private",
                                           "Other" => "Other" } %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :profession, :class => "control-label" %>
            <div class="controls"><%= f.text_field :profession %></div>
          </div>
          <div class="control-group">
            <%= f.label :skills, :class => "control-label" %>
            <div class="controls"><%= f.text_area :skills, :rows => "10" %></div>
          </div>
          <div class="form-actions">
            <%= f.submit :class => "btn-success" %>
          </div>
        </fieldset>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="row">
  <div class="span6">
    <div class="boxes">
      <legend><%= @title %></legend>
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Profession</th>
            <th>Organization</th>
          </tr>
        </thead>
        <tbody>
          <% @profiles.each do |profile| %>
            <tr>
              <td><%= link_to profile.name, profile %></td>
              <td><%= profile.profession %></td>
              <td><%= profile.entity %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @profiles %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="row">
  <div class="span6">
    <div class="boxes">
      
      <% if @profile.errors.any? %>
        <div class="alert alert-error">
        <% @profile.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
        </div>
      <% end %>

      <fieldset>
        <legend><%= @title %></legend>
        <br />
        <dl class="dl-horizontal">
          <dt>Profession</dt>
          <dd>
            <%= @profile.profession %>
          </dd>
          <br />
          <dt>Organization</dt>
          <dd><%= @profile.entity %></dd>
          <br />
          <dt>Entity</dt>
          <dd><%= @profile.orgtype %></dd>
          <br />
          <dt>Skills</dt>
          <dd><%= @profile.skills %></dd>
          <br />
          <% unless @profile.projects.blank? %>
            <dt>Supports or Champions</dt>
            <% @profile.projects.each do |p| %>
              <dd><%= link_to p.title, p %></dd>
            <% end %>
          <% end %>
        </dl>
      </fieldset>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
<div class="row">
  <div class="span6">
    <div class="boxes">
      <%= form_for @project, :html => {:multipart => true,
                                       :class => "form-horizontal"} do |f| %>
        <% if @project.errors.any? %>
          <div class="alert alert-error">
          <% @project.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
          <% end %>
          </div>
        <% end %>

        <fieldset>
          <legend><%= @title %></legend>
          <div class="control-group">
            <%= f.label "Name", :class => "control-label" %>
            <div class="controls"><%= f.text_field :title %></div>
          </div>
          <div class="control-group">
            <%= f.label "Description of the Project", :class => "control-label" %>
            <div class="controls"><%= f.text_area :desc, :rows => "10" %></div>
          </div>
          <div class="control-group">
            <%= f.label "What you need", :class => "control-label" %>
            <div class="controls"><%= f.text_area :need, :rows => "10" %></div>
          </div>
          <div class="form-actions">
            <%= f.submit :class => "btn-success" %>
          </div>
        </fieldset>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<div class="row">
  <div class="span6">
    <div class="boxes">
      <legend><%= @title %></legend>
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Project Champion</th>
          </tr>
        </thead>
        <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td><%= link_to project.title, project %></td>
              <td><%= project.profiles.first.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @projects %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<div class="row">
  <div class="span6">
    <div class="boxes">
      <fieldset>
        
        <legend><%= @title %></legend>
        <br />
        <dl class="dl-horizontal">
          <dt>Champion</dt>
          <dd>
            <%= link_to @project.profiles.first.name, @project.profiles.first %>
          </dd>
          <br />
          <dt>Description</dt>
          <dd><%= @project.desc %></dd>
          <br />
          <dt>What we need</dt>
          <dd><%= @project.need %></dd>
          <br />
          <% unless @project.profiles.drop(1).blank? %>
            <dt>Supporters</dt>
            <% @project.profiles.drop(1).each do |p| %>
              <dd><%= link_to p.name, p %></dd>
            <% end %>
          <% end %>
        </dl>
      </fieldset>
      <div class="buttons">
        <% unless current_user.profile == @project.profiles.first %>
          <% if @relation.blank? %>
            <%= form_for @new_relation do |f| %>
              <%= f.hidden_field :relationship, :value => "Supporter" %>
              <%= f.hidden_field :profile_id, :value => current_user.profile.id %>
              <%= f.hidden_field :project_id, :value => @project.id %>
              <%= f.submit "Support This Project", :class => "btn" %>
              <%#Need to fix this part, not DRY enough and I'm tired%>
              <%= mail_to @project.profiles.first.user.email, "Send Email",
                          :class => "btn btn-info btn-project" %>
            <% end %>
          <% else %>
            <%= link_to "Withdraw Support", @relation, :method => :delete,
                                                       :title => @project.title,
                                                       :class => "btn" %>
            <%= mail_to @project.profiles.first.user.email, "Send Email",
                        :class => "btn btn-info btn-project" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>